[package]
name = "ferrous"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "compiler/ferrousc_main"
]

[dependencies]
ferrousc_main = { path = "compiler/ferrousc_main" }