[package]
name = "ferrousc_llvm"
version = "0.1.0"
edition = "2018"

[dependencies]
ferrousc_lexer = { path = "../ferrousc_lexer" }
ferrousc_parser = { path = "../ferrousc_parser" }
ferrousc_ast = { path = "../ferrousc_ast" }
llvm-sys = "100"